all: lecon3_1 lecon3_2 lecon3_3 lecon3_4 lecon3_3_1
lecon3_1: lecon_3_1.c
	gcc -o lecon_3_1 lecon_3_1.c

lecon3_2: lecon_3_2.c
	gcc -o lecon3_2 lecon_3_2.c

lecon3_3: lecon_3_3.c
	gcc -o lecon3_3 lecon_3_3.c

lecon3_4: lecon_3_4.c
	gcc -o lecon3_4 lecon_3_4.c

lecon3_3_1: lecon_3_3_1.c
	gcc -Wall -o lecon3_3_1 lecon_3_3_1.c
