all: lecon2 lecon2_1 lecon2_2 lecon2_3
lecon2: lecon_2.c
	gcc -o lecon2 lecon_2.c

lecon2_1: lecon_2_1.c
	gcc -o lecon2_1 lecon_2_1.c

lecon2_2: lecon_2_2.c
	gcc -o lecon2_2 lecon_2_2.c

lecon2_3: lecon_2_3.c
	gcc -o lecon2_3 lecon_2_3.c
